[build]
  command = "npm run build"
  publish = "build"

# Handle SPA routing by redirecting all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
[context.production.environment]
  REACT_APP_API_URL = "https://fly-fitness-zone-api.onrender.com"
  REACT_APP_URL = "https://fly-fitness-zone.netlify.app"

# Environment variables for branch deploys
[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://fly-fitness-zone-api-staging.onrender.com"
  REACT_APP_URL = "https://staging--fly-fitness-zone.netlify.app"

# Cache settings for better performance
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"